Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.define "webui-vvm" do |machine|
    machine.ssh.insert_key = false
    machine.vm.network "private_network", ip: "192.168.255.103"
    machine.ssh.private_key_path = [".ssh/vagrant_rsa", "~/.vagrant.d/insecure_private_key"]
    machine.vm.provision "file", source: ".ssh/vagrant_rsa.pub", destination: "~/.ssh/authorized_keys"
  end
end